Merge branch-notes to master
AY2122S1-CS2113T-T10-2/tp pull request #53
Opened 2021-10-03 14:39 UTC by Woolicious98

Add notes add, delete and view functions.

2021-10-03 14:44 UTC, kelvneo requested changes
Nice job on the entire suite of commands, but needs JUnit testing and styling fixes.

2021-10-03 14:44 UTC, kelvneo commented on src/main/java/terminus/command/note/AddCommand.java
> +            throw new InvalidArgumentException("Error: Missing arguments.");
Magic literals

2021-10-03 14:44 UTC, kelvneo commented on src/main/java/terminus/command/note/AddCommand.java
> +    private int totalArg;
Can this be a static final variable?

2021-10-03 14:44 UTC, kelvneo commented on src/main/java/terminus/content/ContentManager.java
> +    final private static String DATA_SEPARATOR = "";
Redundant variable?

2021-10-03 14:48 UTC, 3m0W33D reviewed
Well done!

2021-10-03 14:48 UTC, 3m0W33D commented on src/main/java/terminus/common/CommonFormat.java
> +    final public static String COMMAND_VIEW_FORMAT = COMMAND_VIEW + " {[optional]item number}";
Regarding the format how should we choose to format this?
For mandatory arguments - `<args>`
For optional - `{args}`
?

2021-10-03 14:48 UTC, 3m0W33D commented on src/main/java/terminus/common/Messages.java
> +    final public static String MESSAGE_COMMAND_VIEW = "view all items or view an individual items";
Would need to update modifier for standards,
`public static final`

2021-10-05 03:28 UTC, kelvneo approved these changes
LGTM

2021-10-05 05:27 UTC, 3m0W33D approved these changes
LGTM

2021-10-05 05:28 UTC, merged